version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:${APP_PORT}:5555"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
    volumes:
      - ./src/main/resources:/var
    restart: unless-stopped
